### ISSUE TITLE
Обозначение нулевого вектора (10 билет)

### ISSUE THREAD

**Issue by dima74** [DidenkoAndre/GOSBook#45]
В 10 билете нулевой вектор насколько я понял обозначается через \theta, например:

![image](https://user-images.githubusercontent.com/6505554/41819124-a6dfa036-77c3-11e8-98cf-67b4e1e9b7f9.png)

Возможно будет лучше если \theta заменить на ноль

(`\overset{\rightarrow}{\theta}` → `\overset{\rightarrow}{0}`)

---

Спасибо за полезную книгу!

**Comment by dima74** [comment]
И в этом же 10 билете во второй теореме немного внезапно появляется квадратичная форма Ф_2

![image](https://user-images.githubusercontent.com/6505554/41819590-794a637e-77cb-11e8-976c-2b038c79b498.png)

Наверно было бы здорово что-нибудь про неё сказать предварительно

**Comment by DidenkoAndre** [comment]
Там вообще эти билеты надо заново переписать, но по отношению второго вопроса добавил предварительные детали. 

И да, обозначения -- сложный вопрос. Но мне больше \theta с стрелкой привычна с курсов статов всяких, хотя я подумаю насчет нуля со стрелкой.
